// ARRAY - METODOS

const items = ['garrafa', 'copo', 'mesa', 'cadeira', 'garfo', 'faca']

// PUSH - ADICIONA UM ITEM NO ARRAY 
// LENGTH - MOSTRA A QUANTIDADE DE ITENS DENTRO DO ARRAY
// SORT - ORGANIZA OS ITENS EM ORDEM ALFABETICA

/* SPLICE - REMOVE ITENS ONDE A GENTE QUER EX: items.splice (1,2 'sofa') IRÁ RETIRAR O COPO E A MESA E COLOCAR O SOFA
E ADICIONA ITENS AONDE A GENTE QUER EX: items.splice (1,2) */
/* SLICE - SEPARA O ARRAY A PARTIR DO ITEM QUE VOCÊ INDICAR
EX: const itemSala = items.slice (1,3), IRÁ MOSTRAR SOMENTE COPO/MESA. SE CRIA UMA NOVA VARIAVEL POIS ELE NÃO MODIFICA O ARRAY, MAS SIM
CRIA UM OUTRO ARRAY*/
// POP - TIRA O ULTIMO ITEM DO ARRAY
// SHIFT - TIRA O PRIMEIRO ITEM DO ARRAY

const itemSala = items.slice (1,3)

console.log (itemSala)